// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPlants.Models;

#nullable disable

namespace MyPlants.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyPlants.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackgroundColorHex")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WaterFrequency")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Plants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackgroundColorHex = "#FFD3AD",
                            ImageName = "1",
                            Name = "Kitchen ficus",
                            UserId = "Gwa7mEmjuQcMQ2EepQHg3KyHGtg2",
                            WaterFrequency = 10
                        },
                        new
                        {
                            Id = 2,
                            BackgroundColorHex = "#8BC7FF",
                            ImageName = "1",
                            Name = "Bedroom ficus",
                            UserId = "Gwa7mEmjuQcMQ2EepQHg3KyHGtg2",
                            WaterFrequency = 10
                        },
                        new
                        {
                            Id = 3,
                            BackgroundColorHex = "#ECFFAD",
                            ImageName = "1",
                            Name = "Ficus tineke",
                            UserId = "Gwa7mEmjuQcMQ2EepQHg3KyHGtg2",
                            WaterFrequency = 10
                        },
                        new
                        {
                            Id = 4,
                            BackgroundColorHex = "#FFADDE",
                            ImageName = "6",
                            Name = "Jade plant",
                            UserId = "Gwa7mEmjuQcMQ2EepQHg3KyHGtg2",
                            WaterFrequency = 14
                        },
                        new
                        {
                            Id = 5,
                            BackgroundColorHex = "#E7F3DC",
                            ImageName = "8",
                            Name = "Peace lilly",
                            UserId = "Gwa7mEmjuQcMQ2EepQHg3KyHGtg2",
                            WaterFrequency = 10
                        },
                        new
                        {
                            Id = 6,
                            BackgroundColorHex = "#FFA8A8",
                            ImageName = "3",
                            Name = "Pothos",
                            UserId = "Gwa7mEmjuQcMQ2EepQHg3KyHGtg2",
                            WaterFrequency = 10
                        },
                        new
                        {
                            Id = 7,
                            BackgroundColorHex = "#FFF79D",
                            ImageName = "2",
                            Name = "Sanseveria",
                            UserId = "Gwa7mEmjuQcMQ2EepQHg3KyHGtg2",
                            WaterFrequency = 14
                        },
                        new
                        {
                            Id = 8,
                            BackgroundColorHex = "#FFA8A8",
                            ImageName = "4",
                            Name = "ZZ plant",
                            UserId = "Gwa7mEmjuQcMQ2EepQHg3KyHGtg2",
                            WaterFrequency = 10
                        });
                });

            modelBuilder.Entity("MyPlants.Models.Watering", b =>
                {
                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Fertilized")
                        .HasColumnType("bit");

                    b.HasKey("PlantId", "Date");

                    b.ToTable("Waterings");

                    b.HasData(
                        new
                        {
                            PlantId = 1,
                            Date = new DateTime(2024, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fertilized = false
                        },
                        new
                        {
                            PlantId = 2,
                            Date = new DateTime(2024, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fertilized = false
                        },
                        new
                        {
                            PlantId = 3,
                            Date = new DateTime(2024, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fertilized = false
                        },
                        new
                        {
                            PlantId = 4,
                            Date = new DateTime(2024, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fertilized = false
                        },
                        new
                        {
                            PlantId = 5,
                            Date = new DateTime(2024, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fertilized = false
                        },
                        new
                        {
                            PlantId = 6,
                            Date = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fertilized = false
                        },
                        new
                        {
                            PlantId = 7,
                            Date = new DateTime(2024, 12, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fertilized = false
                        },
                        new
                        {
                            PlantId = 8,
                            Date = new DateTime(2024, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fertilized = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
